// <auto-generated />
using System;
using ElectricityWebApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElectricityWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220430072851_livedb")]
    partial class livedb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ElectricityWebApp.Models.CountryData", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("countryData");
                });

            modelBuilder.Entity("ElectricityWebApp.Models.ElectricityDetails", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitsConsumption")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("electricityDetails");
                });

            modelBuilder.Entity("ElectricityWebApp.Models.Series", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("f")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geography")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("geography2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iso3166")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastHistoricalPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latlon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("latlon2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("series_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("units")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("updated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("series");
                });
#pragma warning restore 612, 618
        }
    }
}
